# Generated by Django 3.2.4 on 2021-07-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raisemodifyorder', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('landmark', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.RemoveField(
            model_name='foodseeker',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='foodseeker',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodseeker',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodseeker',
            name='fs_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodseeker',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_seeker_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
