# Generated by Django 3.2.4 on 2021-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raisemodifyorder', '0009_auto_20210708_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodseeker',
            name='fs_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
