# Generated by Django 3.1.5 on 2021-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('add_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('landmark', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProvider',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('ratings', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSeeker',
            fields=[
                ('fs_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('veg_healthy', models.IntegerField(null=True)),
                ('veg_ill', models.IntegerField(null=True)),
                ('nonveg_healthy', models.IntegerField(null=True)),
                ('nonveg_ill', models.IntegerField(null=True)),
                ('allergies', models.CharField(max_length=200, null=True)),
                ('delivery_address', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('food_seeker_id', models.IntegerField()),
                ('food_provider_id', models.IntegerField(null=True)),
            ],
        ),
    ]
