# Generated by Django 3.1.5 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprovider',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
